{
 "title": "NiFi Monitoring",
 "description": "General view of Nifi \r\n",
 "tags": [ "NiFi" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "nifi_node",
    "query": "label_values(nifi_nodes_status,exported_instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NiFI Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nifi_cluster_version_info", "legendFormat": "{{version}}" }
   ]
  },
  { "title": "General view", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$nifi_node",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "repeat": "nifi_node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_nodes_status{exported_instance=~\"$nifi_node\"}"
    }
   ]
  },
  { "title": "Nodes - Queued Items", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$nifi_node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "repeat": "nifi_node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_node_queuedItems{exported_instance=~\"$nifi_node\"}"
    }
   ]
  },
  { "title": "Nodes - Active Thread Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$nifi_node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "repeat": "nifi_node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nifi_node_activeThreadCount{exported_instance=~\"$nifi_node\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Flow Files Queued",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nifi_cluster_flowFilesQueued" }
   ]
  },
  {
   "title": "Bytes Queued",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    { "expr": "nifi_cluster_bytesQueued" }
   ]
  },
  {
   "title": "General proccessor counters ",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nifi_cluster_stoppedCount", "legendFormat": "Stopped Count" },
    { "expr": "nifi_cluster_invalidCount", "legendFormat": "Invalid Count" },
    { "expr": "nifi_cluster_runningCount", "legendFormat": "Running Count" }
   ]
  },
  { "title": "Queued Item", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Queue item per PG",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nifi_amount_items_queued", "legendFormat": "{{processorName}}" }
   ]
  }
 ]
}