{
 "title": "Nifi_Metrics",
 "description": "This dashboard is used to monitor the metrics related to NiFi ",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "go_gc_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.25\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0.25\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0.5\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"0.75\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"0.75\"}"
    },
    {
     "expr": "go_gc_duration_seconds{instance=~\"$instance\",quantile=\"1\"}",
     "legendFormat": "go_gc_duration_seconds{quantile=\"1\"}"
    },
    {
     "expr": "go_gc_duration_seconds_count{instance=~\"$instance\"}",
     "legendFormat": "go_gc_duration_seconds_count"
    },
    {
     "expr": "go_gc_duration_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "go_gc_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go_goroutines"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_alloc_bytes"
    },
    {
     "expr": "go_memstats_alloc_bytes_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_alloc_bytes_total"
    }
   ]
  },
  {
   "title": "go_memstats_gc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_gc_cpu_fraction"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_gc_sys_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_alloc_bytes"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_idle_bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_inuse_bytes"
    },
    {
     "expr": "go_memstats_heap_objects{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_objects"
    },
    {
     "expr": "go_memstats_heap_released_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_released_bytes"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_heap_sys_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_mallocs/mcache/mspan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mallocs_total"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mcache_inuse_bytes"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mcache_sys_bytes"
    },
    {
     "expr": "go_memstats_mspan_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mspan_inuse_bytes"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_mspan_sys_bytes"
    }
   ]
  },
  {
   "title": "go_memstats_stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_inuse_bytes"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_stack_sys_bytes"
    }
   ]
  },
  {
   "title": "Other metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_buck_hash_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_buck_hash_sys_bytes"
    },
    {
     "expr": "go_memstats_frees_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_frees_total"
    },
    {
     "expr": "go_memstats_last_gc_time_seconds{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_last_gc_time_seconds"
    },
    {
     "expr": "go_memstats_lookups_total{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_lookups_total"
    },
    {
     "expr": "go_memstats_next_gc_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_next_gc_bytes"
    },
    {
     "expr": "go_memstats_other_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_other_sys_bytes"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "go_memstats_sys_bytes"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go_threads"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds(handler=\"delete\")",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_microseconds{handler=\"delete\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.5\"}"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"delete\",instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.9\"}"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"delete\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.99\"}"
    },
    {
     "expr": "http_request_duration_microseconds_count{handler=\"delete\",instance=~\"$instance\"}",
     "legendFormat": "http_request_duration_microseconds_count"
    },
    {
     "expr": "http_request_duration_microseconds_sum{handler=\"delete\",instance=~\"$instance\"}",
     "legendFormat": "http_request_duration_microseconds_sum"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds{handler=\"prometheus\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_microseconds{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.5\"}"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.9\"}"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.99\"}"
    },
    {
     "expr": "http_request_duration_microseconds_count{handler=\"prometheus\",instance=~\"$instance\"}",
     "legendFormat": "http_request_duration_microseconds_count"
    },
    {
     "expr": "http_request_duration_microseconds_sum{handler=\"prometheus\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_duration_microseconds_sum\t"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds{handler=\"push\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_microseconds{handler=\"push\",instance=~\"$instance\",quantile=\"0.5\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.5\"}"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"push\",instance=~\"$instance\",quantile=\"0.9\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.9\"}"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"push\",instance=~\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.99\"}"
    },
    {
     "expr": "http_request_duration_microseconds_count{handler=\"push\",instance=~\"$instance\"}",
     "legendFormat": "http_request_duration_microseconds_count"
    },
    {
     "expr": "http_request_duration_microseconds_sum{handler=\"push\",instance=~\"$instance\"}",
     "legendFormat": "http_request_duration_microseconds_sum"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds{handler=\"static\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_microseconds{handler=\"static\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"static\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"static\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_request_duration_microseconds_count{handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_duration_microseconds_count"
    },
    {
     "expr": "http_request_duration_microseconds_sum{handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_duration_microseconds_sum"
    }
   ]
  },
  {
   "title": "http_request_duration_microseconds{handler=\"status\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_duration_microseconds{handler=\"status\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"status\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_request_duration_microseconds{handler=\"status\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_duration_microseconds{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_request_duration_microseconds_count{handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_duration_microseconds_count"
    },
    {
     "expr": "http_request_duration_microseconds_sum{handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_duration_microseconds_sum"
    }
   ]
  },
  {
   "title": "http_request_size_bytes{handler=\"delete\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_size_bytes{handler=\"delete\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.5\"}"
    },
    {
     "expr": "http_request_size_bytes{handler=\"delete\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.5\"}"
    },
    {
     "expr": "http_request_size_bytes{handler=\"delete\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.99\"}"
    },
    {
     "expr": "http_request_size_bytes_count{handler=\"delete\", instance=~\"$instance\"}",
     "legendFormat": "http_request_size_bytes_count"
    },
    {
     "expr": "http_request_size_bytes_sum{handler=\"delete\", instance=~\"$instance\"}",
     "legendFormat": "http_request_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_request_size_bytes{handler=\"prometheus\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_size_bytes{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_request_size_bytes{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_request_size_bytes{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_request_size_bytes_count{handler=\"prometheus\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_count"
    },
    {
     "expr": "http_request_size_bytes_sum{handler=\"prometheus\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_request_size_bytes{handler=\"push\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_size_bytes{handler=\"push\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.5\"}"
    },
    {
     "expr": "http_request_size_bytes{handler=\"push\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.9\"}"
    },
    {
     "expr": "http_request_size_bytes{handler=\"push\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_request_size_bytes_count{handler=\"push\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_count"
    },
    {
     "expr": "http_request_size_bytes_sum{handler=\"push\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_request_size_bytes{handler=\"static\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_size_bytes{handler=\"static\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_request_size_bytes{handler=\"static\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_request_size_bytes{handler=\"static\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_request_size_bytes_count{handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_count"
    },
    {
     "expr": "http_request_size_bytes_sum{handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_request_size_bytes{handler=\"status\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_request_size_bytes{handler=\"status\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_request_size_bytes{handler=\"status\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_request_size_bytes{handler=\"status\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_request_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_request_size_bytes_count{handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_count"
    },
    {
     "expr": "http_request_size_bytes_sum{handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_request_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_requests_total{code=\"200\",handler=\"prometheus\",instance=~\"$instance\"}\t",
     "legendFormat": "http_requests_total{code=\"200\",handler=\"prometheus\"}\t"
    },
    {
     "expr": "http_requests_total{code=\"200\",handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_requests_total{code=\"200\",handler=\"static\"}\t"
    },
    {
     "expr": "http_requests_total{code=\"200\",handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_requests_total{code=\"200\",handler=\"status\"}\t"
    }
   ]
  },
  {
   "title": "http_response_size_bytes{handler=\"delete\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_response_size_bytes{handler=\"delete\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"delete\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"delete\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"delete\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_count"
    },
    {
     "expr": "http_response_size_bytes_sum{handler=\"delete\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_response_size_bytes{handler=\"push\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_response_size_bytes{handler=\"push\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"push\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"push\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"push\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_count"
    },
    {
     "expr": "http_response_size_bytes_sum{handler=\"push\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_response_size_bytes{handler=\"prometheus\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_response_size_bytes{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"prometheus\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"prometheus\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_count"
    },
    {
     "expr": "http_response_size_bytes_sum{handler=\"prometheus\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_response_size_bytes{handler=\"static\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_response_size_bytes{handler=\"static\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"static\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"static\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_count"
    },
    {
     "expr": "http_response_size_bytes_sum{handler=\"static\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_sum"
    }
   ]
  },
  {
   "title": "http_response_size_bytes{handler=\"status\"}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 208 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_response_size_bytes{handler=\"status\",instance=~\"$instance\",quantile=\"0.5\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.5\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"status\",instance=~\"$instance\",quantile=\"0.9\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.9\"}\t"
    },
    {
     "expr": "http_response_size_bytes{handler=\"status\",instance=~\"$instance\",quantile=\"0.99\"}\t",
     "legendFormat": "http_response_size_bytes{quantile=\"0.99\"}\t"
    },
    {
     "expr": "http_response_size_bytes_count{handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_count"
    },
    {
     "expr": "http_response_size_bytes_sum{handler=\"status\",instance=~\"$instance\"}\t",
     "legendFormat": "http_response_size_bytes_sum"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 217 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=~\"$instance\"}\t",
     "legendFormat": "process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "process_group_amount_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 226 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_group_amount_bytes_total{instance=~\"$instance\",status=\"read\"}\t",
     "legendFormat": "process_group_amount_bytes_total{status=\"read\"}"
    },
    {
     "expr": "process_group_amount_bytes_total{instance=~\"$instance\",status=\"received\"}\t",
     "legendFormat": "process_group_amount_bytes_total{status=\"received\"}"
    },
    {
     "expr": "process_group_amount_bytes_total{instance=~\"$instance\",status=\"sent\"}\t",
     "legendFormat": "process_group_amount_bytes_total{status=\"sent\"}"
    },
    {
     "expr": "process_group_amount_bytes_total{instance=~\"$instance\",status=\"transferred\"}\t",
     "legendFormat": "process_group_amount_bytes_total{status=\"transferred\"}\t"
    },
    {
     "expr": "process_group_amount_bytes_total{instance=~\"$instance\",status=\"written\"}\t",
     "legendFormat": "process_group_amount_bytes_total{status=\"written\"}\t"
    }
   ]
  },
  {
   "title": "process_group_amount_flowfiles_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 235 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_group_amount_flowfiles_total{instance=~\"$instance\",status=\"received\"}\t",
     "legendFormat": "process_group_amount_flowfiles_total{status=\"received\"}\t"
    },
    {
     "expr": "process_group_amount_flowfiles_total{instance=~\"$instance\",status=\"sent\"}\t",
     "legendFormat": "process_group_amount_flowfiles_total{status=\"sent\"}\t"
    },
    {
     "expr": "process_group_amount_flowfiles_total{instance=~\"$instance\",status=\"transferred\"}\t",
     "legendFormat": "process_group_amount_flowfiles_total{status=\"transferred\"}\t"
    }
   ]
  },
  {
   "title": "process_group_amount_items",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_group_amount_items{instance=~\"$instance\",status=\"input\"}\t",
     "legendFormat": "process_group_amount_items{status=\"input\"}\t"
    },
    {
     "expr": "process_group_amount_items{instance=~\"$instance\",status=\"output\"}\t",
     "legendFormat": "process_group_amount_items{status=\"output\"}\t"
    },
    {
     "expr": "process_group_amount_items{instance=~\"$instance\",status=\"queued\"}\t",
     "legendFormat": "process_group_amount_items{status=\"queued\"}\t"
    }
   ]
  },
  {
   "title": "process_group_amount_threads_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 253 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_group_amount_threads_total{instance=~\"$instance\",status=\"nano\"}\t",
     "legendFormat": "process_group_amount_threads_total"
    }
   ]
  },
  {
   "title": "process_group_size_content_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 262 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_group_size_content_total{instance=~\"$instance\",status=\"input\"}\t",
     "legendFormat": "process_group_size_content_total{status=\"input\"}\t"
    },
    {
     "expr": "process_group_size_content_total{instance=~\"$instance\",status=\"output\"}\t",
     "legendFormat": "process_group_size_content_total{status=\"output\"}\t"
    },
    {
     "expr": "process_group_size_content_total{instance=~\"$instance\",status=\"queued\"}\t",
     "legendFormat": "process_group_size_content_total{status=\"queued\"}\t"
    }
   ]
  },
  {
   "title": "process_metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 271 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\"}\t",
     "legendFormat": "process_max_fds"
    },
    {
     "expr": "process_open_fds{instance=~\"$instance\"}\t",
     "legendFormat": "process_open_fds"
    },
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}\t",
     "legendFormat": "process_resident_memory_bytes"
    },
    {
     "expr": "process_start_time_seconds{instance=~\"$instance\"}\t",
     "legendFormat": "process_start_time_seconds"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}\t",
     "legendFormat": "process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "pushgateway_build_info",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 280 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pushgateway_build_info{branch=\"master\",goversion=\"go1.8.3\",instance=~\"$instance\",revision=\"6ceb4a19fa85ac2d6c2d386c144566fb1ede1f6c\",version=\"0.4.0\"}\t",
     "legendFormat": "pushgateway_build_info"
    }
   ]
  }
 ]
}