{
 "title": "Spark Queries for Structured Streaming",
 "description": "Just plotting of all metrics, produced by enabled Prometheus output of Spark Structured Streaming jobs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "spark_driver_structured_streaming_latency_type_gauges",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"spark_driver_structured_streaming_latency_type_gauges.*\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "spark_driver_structured_streaming_inputrate_total_type_gauges",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"spark_driver_structured_streaming_inputrate_total_type_gauges.*\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "spark_driver_structured_streaming_states_rowstotal_type_gauges",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"spark_driver_structured_streaming_states_rowstotal_type_gauges.*\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "spark_driver_structured_streaming_processingrate_total_type_gauges",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"spark_driver_structured_streaming_processingrate_total_type_gauges.*\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "spark_driver_structured_streaming_eventtime_watermark_type_gauges",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"spark_driver_structured_streaming_eventtime_watermark_type_gauges.*\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  }
 ]
}